name: validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to validate"
        required: true
        default: "staging"
        type: choice
        options:
          - prod
          - staging
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        run: cargo test --test integration
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          RPC_PROXY_INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          RPC_PROXY_REGISTRY_API_URL: ${{ secrets.REGISTRY_URL }}
          RPC_PROXY_REGISTRY_API_AUTH_TOKEN: ${{ secrets.RPC_PROXY_REGISTRY_API_AUTH_TOKEN }}
          RPC_PROXY_POKT_PROJECT_ID: ${{ secrets.POKT_PROJECT_ID }}
          RPC_URL: ${{ inputs.environment_url }}
