name: validate

on:
  workflow_call:
    inputs:
      environment_url:
        description: "the environment to validate"
        required: true
        default: "https://staging.rpc.walletconnect.com"
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3         

      - name: Run integration tests
        run: cargo test --test integration
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
         